name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set image tag
        id: set_tag
        run: |
          IMAGE_TAG=""
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            # Remove any ".x" suffixes from the branch name
            BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's/\.x$//')
            IMAGE_TAG=":$BRANCH_NAME"
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}${{ steps.set_tag.outputs.IMAGE_TAG }}
